### PR TITLE
Update allowlist.yaml

### PR DESCRIPTION
**Pull request by alexgibson**
Fixes https://github.com/mozmeao/www-site-checker/actions/runs/2769835130

### CODE REVIEW

**Review by stevejalim — APPROVED** [review]
Thanks for picking this up. Feedback on how painful it was welcome next week :)

There's also a `https://www.projectfluent.org/` around line 1250ish - if you want to move that up to join your addition, feel free but I can tweak next time

r+wc

**Comment by alexgibson** [comment]
Hmm, not sure I follow this - I see https://projectfluent.org/ is already in the list twice. Why is it failing, and why do we need to add it a third time?

**Comment by alexgibson** [comment]
Ok, moved `www.projectfluent.org` up, and removed the existing duplicate. Still not 100% clear why it was failing though

**Comment by stevejalim** [comment]
Will look when am back but I see https://www.projectfluent.org/ and
https://projectfluent.org/ in the allowlist already. The string matching
(not the regexes at the top) is a check for a the full string so if the
check was failing because it found a projectfluent.org URL with no trailing
slash, that would explain it. Am not able to unzip the artifact file on my
phone to see. Long shot, mind you. Will look later

**Comment by stevejalim** [comment]
Ah looks like the HTML parser is pulling out that link with a leading space, which causes a matching fail - have ticketed this (#15) and will add it as a temporary exception. Merging this PR - thanks Alex!

**Pull request merged**
